version: '3'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE} -schemas=myschema -user=flyway_user -password=${FLYWAY_USER_PASSWORD} -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
