name: MySQL Build

on:
  push:
    branches:
      - main

jobs:
  database-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build MySQL Docker image
        run: docker build -t dongne-mysql-image --build-arg MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} -f database/Dockerfile.mysql .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push MySQL Docker image to Docker Hub
        run: docker push dongne-mysql-image
