name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Compose Environment Variables
        run: |
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "FLYWAY_USER_PASSWORD=${{ secrets.FLYWAY_USER_PASSWORD }}" >> .env

      - name: Build and Push Docker Images
        run: docker-compose build --build-arg MYSQL_ROOT_PASSWORD_ARG="${{ secrets.MYSQL_PASSWORD }}" --build-arg MYSQL_DATABASE_ARG="${{ secrets.MYSQL_DATABASE }}"
      
      - name: Start Docker Services
        run: |
          docker-compose up -d
  
  mysql-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build MySQL Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dongnae-mysql-image --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} -f database/Dockerfile.mysql .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push MySQL Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dongnae-mysql-image

  setup-flyway-user:
    runs-on: ubuntu-latest

    needs: [mysql-build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start MySQL container
        run: docker-compose up -d mysql

      - name: Wait for MySQL to start
        run: |
          until mysqladmin ping -h mysql --silent; do
              echo 'Waiting for MySQL to start...'
              sleep 1
          done

      - name: Create Flyway user and grant privileges
        run: |
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE USER IF NOT EXISTS 'flyway_user'@'%' IDENTIFIED BY '${{ secrets.FLYWAY_USER_PASSWORD }}';"
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'flyway_user'@'%';"
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "FLUSH PRIVILEGES;"

      - name: Build Flyway Docker image
        run: docker build -t dongnae-flyway-image --build-arg FLYWAY_URL=jdbc:mysql://mysql:3306/${{ secrets.MYSQL_DATABASE }} --build-arg FLYWAY_USER=flyway_user --build-arg FLYWAY_PASSWORD=${{ secrets.FLYWAY_USER_PASSWORD }} -f database/Dockerfile.flyway .

      - name: Run Flyway migrations
        run: docker run dongnae-flyway-image
