name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Compose Environment Variables
        run: |
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "FLYWAY_USER_PASSWORD=${{ secrets.FLYWAY_USER_PASSWORD }}" >> .env

      - name: Build and Push Docker Images
        run: docker-compose build --build-arg MYSQL_ROOT_PASSWORD_ARG="${{ secrets.MYSQL_PASSWORD }}" --build-arg MYSQL_DATABASE_ARG="${{ secrets.MYSQL_DATABASE }}"
          docker-compose up -d
