name: Setup Flyway User

on:
  push:
    branches:
      - main

jobs:
  setup-flyway-user:
    runs-on: ubuntu-latest

    needs: [database-build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start MySQL container
        run: docker-compose up -d mysql

      - name: Wait for MySQL to start
        run: |
          until mysqladmin ping -h mysql --silent; do
              echo 'Waiting for MySQL to start...'
              sleep 1
          done

      - name: Create Flyway user and grant privileges
        run: |
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE USER IF NOT EXISTS 'flyway_user'@'%' IDENTIFIED BY '${{ secrets.FLYWAY_USER_PASSWORD }}';"
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'flyway_user'@'%';"
          docker exec mysql mysql -uroot -p"${{ secrets.MYSQL_PASSWORD }}" -e "FLUSH PRIVILEGES;"
