name: Flyway Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    needs: [setup-flyway-user]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Flyway Docker image
        run: docker build -t dongne-flyway-image --build-arg FLYWAY_URL=jdbc:mysql://my-mysql-container:3306/mydatabase --build-arg FLYWAY_USER=myuser --build-arg FLYWAY_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -f Dockerfile.flyway .

      - name: Run Flyway migrations
        run: docker run dongne-flyway-image
